In [1]:
import numpy as np

lst = [10, 20, 30, 40, 50]
arr = np.array(lst)

print("Array:", arr)
print("Shape:", arr.shape)
print("Data Type:", arr.dtype)


Array: [10 20 30 40 50]
Shape: (5,)
Data Type: int64


In [2]:
import numpy as np

zeros_matrix = np.zeros((3, 3))
ones_matrix = np.ones((2, 5))

print("3x3 Zero Matrix:\n", zeros_matrix)
print("Shape:", zeros_matrix.shape)

print("\n2x5 Ones Matrix:\n", ones_matrix)
print("Shape:", ones_matrix.shape)


3x3 Zero Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Shape: (3, 3)

2x5 Ones Matrix:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Shape: (2, 5)


In [3]:
import numpy as np

arr = np.arange(1, 13)
reshaped_arr = arr.reshape(3, 4)

print("Original Array:", arr)
print("Original Shape:", arr.shape)

print("\nReshaped Array:\n", reshaped_arr)
print("Reshaped Shape:", reshaped_arr.shape)


Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Original Shape: (12,)

Reshaped Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshaped Shape: (3, 4)


In [4]:
import numpy as np

arr = np.random.randint(1, 100, 10)

print("Array:", arr)
print("Minimum:", arr.min())
print("Maximum:", arr.max())
print("Mean:", arr.mean())
print("Sum:", arr.sum())


Array: [90 54 46 74 53  5 94 79 31 59]
Minimum: 5
Maximum: 94
Mean: 58.5
Sum: 585


In [5]:
import pandas as pd

data = {
    "Student_Name": ["Arshi", "Aman", "Riya", "Karan"],
    "Marks": [85, 90, 78, 88]
}

df = pd.DataFrame(data)

print(df)
print("\nData Types:\n", df.dtypes)


  Student_Name  Marks
0        Arshi     85
1         Aman     90
2         Riya     78
3        Karan     88

Data Types:
 Student_Name    object
Marks            int64
dtype: object


In [8]:
import pandas as pd

data = {
    "Name": ["Arshi", "Aman", "Riya", "Karan", "Neha", "Rahul"],
    "Marks": [85, 90, 78, 88, 92, 80]
}

df = pd.DataFrame(data)
df.to_csv("data.csv", index=False)

print("CSV file created successfully")


CSV file created successfully


In [9]:
import pandas as pd

df = pd.read_csv("data.csv")

print("First 5 Records:\n", df.head())
print("\nLast 5 Records:\n", df.tail())


First 5 Records:
     Name  Marks
0  Arshi     85
1   Aman     90
2   Riya     78
3  Karan     88
4   Neha     92

Last 5 Records:
     Name  Marks
1   Aman     90
2   Riya     78
3  Karan     88
4   Neha     92
5  Rahul     80


In [10]:
import pandas as pd

df = pd.read_csv("data.csv")

print("Number of Rows:", df.shape[0])
print("Number of Columns:", df.shape[1])
print("\nMissing Values:\n", df.isnull().sum())


Number of Rows: 6
Number of Columns: 2

Missing Values:
 Name     0
Marks    0
dtype: int64


In [11]:
import pandas as pd

df = pd.read_csv("data.csv")

print(df.describe())



           Marks
count   6.000000
mean   85.500000
std     5.576737
min    78.000000
25%    81.250000
50%    86.500000
75%    89.500000
max    92.000000
