In [ ]:
import numpy as np
a = np.array([1, 2, 3])
print(a)


[1 2 3]


In [ ]:
b = np.array([[1, 2, 3],
              [4, 5, 6]])
print(b)


[[1 2 3]
 [4 5 6]]


In [ ]:
c = np.array([1, 2, 3], dtype=float)
print(c)


[1. 2. 3.]


In [ ]:
d = np.array([[1, 2],
              [3, 4],
              [5, 6],
              [7, 8]])
print(d)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
e = np.arange(10)
print(e)


[0 1 2 3 4 5 6 7 8 9]


In [ ]:
f = np.arange(16).reshape(2, 2, 2, 2)
print(f)


[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


In [ ]:
g = np.ones((2, 4))
print(g)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
h = np.random.random((3, 4))
print(h)



[[0.01483282 0.67890403 0.20327076 0.34748413]
 [0.10415059 0.94729902 0.44540789 0.539987  ]
 [0.92290413 0.04461159 0.80509274 0.06252156]]


In [ ]:
i = np.identity(3)
print(i)



[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
print("Shape:", h.shape)
print("Size:", h.size)
print("Data Type:", h.dtype)


Shape: (3, 4)
Size: 12
Data Type: float64
